export default {
    "00-our-father": import("./00-our-father.json"),
    "01-introduction-to-the-creed": import("./01-introduction-to-the-creed.json"),
    "02-the-orthodox-creed": import("./02-the-orthodox-creed.json"),
    "03-procession-of-the-lamb": import("./03-procession-of-the-lamb.json"),
    "04-khen-efran": import("./04-khen-efran.json"),
    "04-lord-have-mercy": import("./04-lord-have-mercy.json"),
    "05-holy-holy-holy": import("./05-holy-holy-holy.json"),
    "05-thanksgiving-prayer": import("./05-thanksgiving-prayer.json"),
    "06-absolution-of-the-servants": import("./06-absolution-of-the-servants.json"),
    "06-alleluia-fai-be-pi": import("./06-alleluia-fai-be-pi.json"),
    "07-khen-efran": import("./07-khen-efran.json"),
    "08-absolution-of-the-servants": import("./08-absolution-of-the-servants.json"),
    "08-thanksgiving-prayer": import("./08-thanksgiving-prayer.json"),
    "09-absolution-of-the-servants": import("./09-absolution-of-the-servants.json"),
    "09-thanksgiving-prayer": import("./09-thanksgiving-prayer.json"),
};
